name: geometricweather_flutter
description: An Flutter vairant for GeometricWeather.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0

  intl: ^0.17.0
  provider: ^5.0.0
  package_info: ^2.0.2
  url_launcher: ^5.0.3
  get_it: ^1.0.3+2
  flutter_sensors: ^0.1.5
  flutter_platform_widgets: ^1.8.1
  floor: ^1.1.0
  dio: ^4.0.0
  json_serializable: ^4.1.3
  geolocator: ^7.0.3
  shared_preferences: ^2.0.6
  timezone: ^0.7.0
  flutter_native_timezone: ^1.1.0
  native_device_orientation: ^1.0.0
  flutter_staggered_animations: ^1.0.0
  ink_page_indicator: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.1.0
  json_serializable: ^4.1.3
  build_runner: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/ic_launcher.png
    - images/weather_clear_day.png
    - images/weather_clear_day.png
    - images/weather_clear_night.png
    - images/weather_cloudy.png
    - images/weather_fog.png
    - images/weather_hail.png
    - images/weather_haze.png
    - images/weather_partly_cloudy_day.png
    - images/weather_partly_cloudy_night.png
    - images/weather_rain.png
    - images/weather_sleet.png
    - images/weather_snow.png
    - images/weather_thunder.png
    - images/weather_thunderstorm.png
    - images/weather_wind.png
    - images/donate_wechat.png
    - images/donate_alipay.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_intl:
  enabled: true